# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: 0.2.0

  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify Windows Version
        allowPrerelease: true
      settings:
        MinVersion: "10.0.19041"

  resources:

    #
    # Windows Configuration
    #

    - resource: Microsoft.Windows.Developer/DeveloperMode
      id: EnableDeveloperMode
      directives:
        description: Enable Developer Mode
        allowPrerelease: true
      settings:
        Ensure: Present

    - resource: PSDscResources/Registry
      id: ShowHiddenFiles
      directives:
        description: Show Hidden Files
      settings:
        Key: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        ValueName: Hidden
        ValueType: DWord
        ValueData: 1
        Force: true

    - resource: PSDscResources/Registry
      id: ShowFileExtensions
      directives:
        description: Show File Extensions
      settings:
        Key: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        ValueName: HideFileExt
        ValueType: DWord
        ValueData: 0
        Force: true

    #
    # Core Apps and Tools
    #

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Sysinternals
      directives:
        description: Install Sysinternals
        allowPrerelease: true
      settings:
        id: '9P7KNL5RWT25'
        source: msstore

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Git
      directives:
        description: Install Git
        allowPrerelease: true
      settings:
        id: Git.Git
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: PowerShell
      directives:
        description: Install PowerShell Core
        allowPrerelease: true
      settings:
        id: Microsoft.PowerShell
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: .NET
      directives:
        description: Install .NET SDK
        allowPrerelease: true
      settings:
        id: Microsoft.DotNet.SDK.Preview
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: VSCode
      directives:
        description: Install VSCode
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudioCode
        source: winget
